services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
      
  api:
    container_name: todo_api
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.http.routers.todo_api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo_api.entrypoints=websecure"
      - "traefik.http.routers.todo_api.tls.certresolver=myresolver"
      - "traefik.http.routers.todo_api.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.todo_api.tls.domains[0].sans=www.${DOMAIN}"

networks:
  default:
    external: 
      name: traefik      